# graph/state.py
"""
Graph State Module
------------------
Defines the shared state object passed between LangGraph nodes.
"""

from typing import Any, Dict, List, TypedDict

from core.types import Document


class AgentState(TypedDict, total=False):
    """
    Represents the state of the agentic pipeline.
    
    Attributes:
        user_input (str): The original user query.
        intent (Dict): Parsed intent metadata.
        plan (Dict): The execution plan generated by the planner.
        agent_outputs (List[Dict]): Results from executed agents.
        retrieved_docs (List[Document]): Documents retrieved for RAG.
        summary (str): Intermediate summary.
        final_report (str): The final markdown report.
    """
    user_input: str
    intent: Dict[str, Any]
    plan: Dict[str, Any]
    agent_outputs: List[Dict[str, Any]]
    retrieved_docs: List[Document]
    summary: str
    final_report: str
